[package]
name = "shahanshahi-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
serde = { version="1", features=["derive"] }
serde_json="1"
clap = { version="4", features=["derive"] }